services:
  - type: web
    name: kidquest-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && python -c 'from app import app; from models import db; app.app_context().push(); db.create_all()' && gunicorn --bind 0.0.0.0:$PORT app:app"
    disk:
      name: kidquest-data
      mountPath: /opt/render/project/src/backend/instance
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///./instance/app.db"
      - key: GROQ_API_KEY
        value: "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"
      - key: OPENROUTER_API_KEY
        value: "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"
      - key: OPENROUTER_API_URL
        value: "https://openrouter.ai/api/v1/chat/completions"
      - key: FLASK_ENV
        value: "production"

disks:
  - name: kidquest-data
    sizeGB: 1
